
# itembankdb.py - Software by Michiel Overtoom, motoom@xs4all.nl

easy = (
    ('0006.jpg', 'een', 'Brandnetel', 'Deze plant kun je beter niet aanraken!', 'Frank Vincentz', 'cc'),
    ('0005.jpg', 'een', 'Boterbloem', 'Deze bloem is giftig voor vee, maar aangezien ze helemaal niet lekker zijn, is dat geen probleem.', 'Kurt Stueber', 'cc'),
    ('0010.jpg', 'een', 'Distel', 'Deze plant prikt!', 'Kurt Stueber', 'cc'),
    ('0033.jpg', 'een', 'Klaproos', 'Als je deze bloem plukt, verlept-ie heel snel.', 'Rob Hooft', 'cc'),
    ('0038.jpg', 'een', 'Madeliefje', 'Deze bloem groeit overal in het gras.', 'Tom.k', 'cc'),
    ('0042.jpg', 'een', 'Narcis', 'Dit bolgewas vermeerdert zich vanzelf, en elk jaar zullen er meer bloemetjes komen.', 'Martin Hirtreiter', 'cc'),
    ('0044.jpg', 'een', 'Paardenbloem', 'Het jonge blad van deze plant wordt wel gegeten, het heet dan \'molsla\'.', 'Sebastian Stabinger/Paethon', 'cc'),
    ('0058.jpg', 'een', 'Sneeuwklokje', 'Deze bloem bloeit al heel vroeg in het voorjaar.', 'Caroig', 'cc'),
    ('0062.jpg', 'een', 'Tulp', 'Deze bloem wordt in allerlei kleuren gekweekt. Nederland is een van de grootste exportlanden ervan.', 'Robert F. Carter/Bettycrocker', 'cc'),
    ('0066.jpg', '', 'Witte klaver', 'Als deze plant vier blaadjes heeft, brengt-ie geluk.', 'Leo Michels', 'pd'),
    ('0070.jpg', 'een', 'Zonnebloem', 'Deze bloem wordt veelal gekweekt om de zaden, waaruit olie wordt geperst, of die bv. in salade gebruikt kunnen worden.', 'Peter Heeling', 'pd'),
)

medium = (
    ('0001.jpg', 'een', 'Akkerviooltje', 'Dit is een op bouwland veel voorkomende plant en wordt als een onkruid gezien.', 'Rasbak', 'cc'),
    ('0004.jpg', '', 'Bieslook', 'Deze plant is verwant aan de ui, prei en knoflook, en wordt gebruikt in salade en kruidenboter.', 'Patrick Reijnders', 'cc'),
    ('0007.jpg', '', 'Brem', 'Deze plant komt zeer algemeen voor, vooral op zandgrond, heidevelden, in duinen en langs spoordijken.', 'MPF Newcastle', 'cc'),
    ('0008.jpg', 'een', 'Dahlia', 'Deze bloem wordt in grote mate gebruikt voor bloemen-corso\'s omdat-ie in vele kleuren voorkomt, en sterk is.', 'KayEss', 'cc'),
    ('0009.jpg', '', 'Dille', 'Deze plant is een kruid met een heel verfijnde smaak, en wordt veel bij vis gebruikt.', 'Toubib', 'cc'),
    ('0012.jpg', 'een', 'Dovenetel', 'Deze plant ziet eruit alsof-ie prikt, maar doet dat niet!', 'TeunSpaans', 'cc'),
    ('0017.jpg', 'een', 'Gewone berenklauw', 'Deze plant moet je niet aanraken, want dat kan tot huidirritatie leiden.', 'Christian Fischer', 'cc'),
    ('0022.jpg', 'een', 'Grote weegbree', 'Deze plant wordt soms beschouwd als onkruid. Hij komt voor in veel tuinen en langs wegen en paden.', 'Rasbak', 'cc'),
    ('0027.jpg', 'een', 'Hyacinth', 'Deze geurige bloem komt oorspronkelijk uit Syri&euml; en Irak, en is in cd 16e eeuw in Europa populair geworden.', 'Rasbak', 'cc'),
    ('0029.jpg', 'een', 'Kamille', 'Deze bloemen worden gebruikt om thee van te maken.', 'Penarc', 'cc'),
    ('0030.jpg', 'een', 'Kamperfoelie', 'Deze slingerplant heeft vooral \'s avonds een sterke zoete geur.', 'Rex', 'pd'),
    ('0032.jpg', 'een', 'Kerstster', 'Deze mooigekleurde bloemen waren de lievelingsbloemen van de aztekenkoning Montezuma II.', 'Scott Bauer', 'pd'),
    ('0035.jpg', 'een', 'Komkommer', 'De vruchten van deze plant wordt als groente gegeten.', 'USDA', 'pd'),
    ('0036.jpg', 'een', 'Korenbloem', 'Deze bloem dankt zijn naam aan zijn traditionele groeiplaats.', 'Maximilian Buehn', 'cc'),
    ('0039.jpg', 'een', 'Margriet', 'Deze bloem wordt vaak voor de sier in gazontuinen gebruikt.', 'sannse', 'cc'),
    ('0040.jpg', '', 'Mimosa', 'Deze bloemen kenmerken zich door kleine blaadjes en de vele stampers.', 'Eric Hunt', 'cc'),
    ('0045.jpg', '', 'Pepermunt', 'Deze plant wordt wel gebruikt om thee van te maken.', 'Sten Porse', 'cc'),
    ('0048.jpg', 'een', 'Reuzenbereklauw', 'Deze plant moet je niet aanraken, want je kunt er brandwonden van krijgen.', 'GerardM', 'cc'),
    ('0051.jpg', '', 'Rode klaver', 'Deze plant werd vroeger veel gebruik om aan vee te voeren.', 'Rasbak', 'cc'),
    ('0053.jpg', '', 'Rozemarijn', 'Deze geurige plant wordt in de keuken gebruikt om gerechten te kruiden.', 'Jean Tosti', 'cc'),
    ('0060.jpg', '', 'Thijm', 'Deze aromatische plant wordt gebruikt om gerechten te kruiden, maar ook in zeep.', 'Kurt Stueber', 'cc'),
    ('0061.jpg', 'een', 'Tuinanjer', 'Werd vroeger als geneesmiddel gebruikt, maar tegenwoordig gekweekt voor de sier.', 'Darkone', 'cc'),
    ('0065.jpg', '', 'Vlas', 'Deze plant wordt al meer dan zesduizend jaar geteeld om linnen van te maken.', 'Rasbak', 'cc'),
)

hard = (
    ('0000.jpg', 'een', 'Aardpeer', 'De eetbare wortelknollen van deze woekerplant worden wel \'Jeruzalemartisjokken\' genoemd.', 'Paul Fenwick', 'cc'),
    ('0002.jpg', 'een', 'Anemoon', 'Deze bloem, die in veel kleuren voorkomt, is familie van de boterbloem.', 'Rex', 'pd'),
    ('0003.jpg', 'een', 'Aster', 'Deze tuinplant komt van origine uit Noord-Amerika.', 'TeunSpaans', 'cc'),
    ('0011.jpg', 'een', 'Dotterbloem', 'Deze plant houdt van sloten, vochtige weilanden, en andere zompige plaatsen.', 'TeunSpaans', 'cc'),
    ('0013.jpg', '', 'Echte kervel', 'Deze plant wordt gebruikt als keukenkruid. In Belgi&euml; wordt er soep van gemaakt.', 'RasBak', 'cc'),
    ('0014.jpg', '', 'Fluitenkruid', 'Deze plant komt veel voor in wegbermen die hierdoor wit gekleurd worden.', 'Rasbak', 'cc'),
    ('0015.jpg', 'een', 'Freesia', 'Omdat deze bloem zo lekker ruikt, wordt-ie wel gebruikt in zeep, shampo, kaarsen etc...', 'Jeantosti', 'cc'),
    ('0016.jpg', '', 'Gember', 'De wortels van deze plant wordt in de keuken gebruikt.', 'Aruna', 'cc'),
    ('0018.jpg', '', 'Gipskruid', 'Deze plant houdt van een kalkachtige grond, en is daar ook naar genoemd.', 'KENPEI', 'cc'),
    ('0019.jpg', 'een', 'Goudzuring', 'Deze plant komt voor op natte, drooggevallen grond en opgespoten terreinen.', 'Christian Fischer', 'cc'),
    ('0020.jpg', 'een', 'Groot hoefblad', 'Deze plant heeft zeer grote bladeren en groeit langs oevers van water.', 'Roger Griffith', 'pd'),
    ('0021.jpg', 'een', 'Grote kattestaart', 'Deze plant werd vroeger gebruikt in de leerlooierij gebruikt. Wortelsap levert een rode kleurstof voor het verven van wol.', 'Radomil', 'cc'),
    ('0023.jpg', 'een', 'Gulden sleutelbloem', 'Deze plant komt voor in weilanden en bossen.', 'Rasbak', 'cc'),
    ('0024.jpg', 'een', 'Guldenroede', 'De uitvinder Thomas Edison probeerde van deze plant rubber te maken.', 'Pethan', 'cc'),
    ('0025.jpg', 'een', 'Hondsviooltje', 'Deze bloem komt voor op voedselarme grond in de duinen, in schrale graslanden, bermen en heidevelden.', 'b.gliwa', 'cc'),
    ('0026.jpg', 'een', 'Hortensia', 'Deze bloem is populair vanwege zijn felle kleuren.', 'P.J.L Laurens', 'cc'),
    ('0028.jpg', 'een', 'Iris', 'Afbeeldingen van deze bloemen zijn al te vinden in de Egyptische pyramiden.', 'Jerzy Opiola', 'cc'),
    ('0031.jpg', 'een', 'Keizerskroon', 'Deze bloemen schrikken mollen af, en ook voor mensen ruiken ze niet lekker.', 'Magalhaes', 'pd'),
    ('0034.jpg', 'een', 'Klein hoefblad', 'De Romeinen gebruikten deze plant als genotmiddel door deze te roken in een pijp.', 'Teun Spaans', 'cc'),
    ('0037.jpg', 'een', 'Lelietje van dalen', 'De geur van deze bloemen wordt veel gebruikt in de parfumerie en de cosmetica. Het is de nationale bloem van Finland.', 'Olegivvit', 'cc'),
    ('0041.jpg', 'een', 'Muizenoor', 'Deze plant heeft zijn naam te danken aan de behaarde bladeren.', 'Kurt Stueber', 'cc'),
    ('0043.jpg', 'een', 'Orchidee', 'De familie van deze plant omvat wel 20.000 soorten.', 'Roepers', 'cc'),
    ('0046.jpg', '', 'Phlox', 'Deze plant laat zich makkelijk stekken.', 'Atilin', 'pd'),
    ('0047.jpg', 'een', 'Pioen', 'Deze geurige bloem, die mieren aantrekt, is een nationaal symbool van China.', 'Fanghong', 'cc'),
    ('0049.jpg', 'een', 'Ridderspoor', 'Deze giftige plant is zeer geliefd bij bijen en vlinders.', 'Stan Shebs', 'cc'),
    ('0050.jpg', 'een', 'Ridderzuring', 'Soms wordt deze plant beschouwd als een zeer hardnekkig onkruid.', 'Sten Porse', 'cc'),
    ('0052.jpg', 'een', 'Rode zijdeplant', 'Deze plant is een favoriet van de monarchvlinder, die de bloemen eet en haar eieren legt op de plant.', 'Teune', 'cc'),
    ('0054.jpg', 'een', 'Ruige weegbree', 'Deze plant groeit op tamelijk droge, grazige plekken, zoals weilanden, dijken en bermen.', 'Sten', 'cc'),
    ('0055.jpg', 'een', 'Sint janskruid', 'Deze plant werd vroeger als geneesmiddel gebruikt.', 'Michael H. Lemmer', 'cc'),
    ('0056.jpg', 'een', 'Slaapbol', 'Deze plant levert maanzaad, wat gebruikt wordt op broodjes.', 'Louise Joly', 'cc'),
    ('0057.jpg', 'een', 'Smalle weegbree', 'Deze plant komt veel voor in allerlei graslanden.', 'Hans Hillewaert', 'cc'),
    ('0059.jpg', 'een', 'Stengelloze sleutelbloem', 'Deze plant is zeldzaam groeit op grazige plaatsen, bijvoorbeeld in de duinen en in Drenthe.', 'Teun Spaans', 'cc'),
    ('0063.jpg', '', 'Valeriaan', 'Deze bloem heeft op katten een onweerstaanbare en sterk prikkelende werking.', 'Pethan', 'cc'),
    ('0064.jpg', '', 'Vetkruid', 'Deze tuinplant wordt in Duitsland als dakbegroeiing gebruikt.', 'Darkone', 'cc'),
    ('0067.jpg', '', 'Zeepkruid', 'De wortels van de plant werden vroeger gebruik om wasgoed te bleken.', 'Teun Spaans', 'cc'),
    ('0068.jpg', 'een', 'Zevenblad', 'De bladeren van deze plant werden wel gegeten als een soort spinazie.', 'Caronna', 'cc'),
    ('0069.jpg', 'een', 'Zinkviooltje', 'Deze bloem heeft zich aangepast aan bepaalde mijngebieden.', 'Friedrich Holtz', 'cc'),
)

itembanks = (
    ("Alledaagse bloemen",
        easy,
        "<p>We beginnen met de makkelijke bloemen, eens kijken hoe goed je ze kunt herkennen!</p><p>Als je een bloem fout raadt, is dat niet erg, dan laat ik je het goede antwoord zien.</p><p>Begin maar!</p>",
        "<p>Goed gedaan, je kent nu alle makkelijke bloemen. Op naar de moeilijker bloemen!</p>",
        ),
    ("Makkelijke bloemen",
        medium,
        "<p>Nu dan de iets moeilijker bloemen.</p><p>Eens kijken hoe goed je ze kunt herkennen!</p>",
        "<p>Bravo! Er zijn n&oacute;g moeilijker bloemen... Ben je er klaar voor?</p>",
        ),
    ("Moeilijke bloemen",
        hard,
        "<p>Tot slot, de moeilijkste bloemen.</p><p>Eens kijken hoe goed je ze kunt herkennen!</p>",
        "<p>Dat was het. Je kent nu alle bloemen die op deze website staan. Fantastisch!</p>",
        ),
    )
